# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cookie_store.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cookie_store.proto',
  package='cs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63ookie_store.proto\x12\x02\x63s\"}\n\x06\x43ookie\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0e\n\x06secure\x18\x05 \x01(\x08\x12\x10\n\x08httpOnly\x18\x06 \x01(\x08\x12\x16\n\x0e\x65xpirationTime\x18\x07 \x01(\x03\"(\n\tCookieJar\x12\x1b\n\x07\x63ookies\x18\x01 \x03(\x0b\x32\n.cs.Cookieb\x06proto3')
)




_COOKIE = _descriptor.Descriptor(
  name='Cookie',
  full_name='cs.Cookie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cs.Cookie.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cs.Cookie.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='cs.Cookie.domain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='cs.Cookie.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secure', full_name='cs.Cookie.secure', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='httpOnly', full_name='cs.Cookie.httpOnly', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expirationTime', full_name='cs.Cookie.expirationTime', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=151,
)


_COOKIEJAR = _descriptor.Descriptor(
  name='CookieJar',
  full_name='cs.CookieJar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cookies', full_name='cs.CookieJar.cookies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=193,
)

_COOKIEJAR.fields_by_name['cookies'].message_type = _COOKIE
DESCRIPTOR.message_types_by_name['Cookie'] = _COOKIE
DESCRIPTOR.message_types_by_name['CookieJar'] = _COOKIEJAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cookie = _reflection.GeneratedProtocolMessageType('Cookie', (_message.Message,), dict(
  DESCRIPTOR = _COOKIE,
  __module__ = 'cookie_store_pb2'
  # @@protoc_insertion_point(class_scope:cs.Cookie)
  ))
_sym_db.RegisterMessage(Cookie)

CookieJar = _reflection.GeneratedProtocolMessageType('CookieJar', (_message.Message,), dict(
  DESCRIPTOR = _COOKIEJAR,
  __module__ = 'cookie_store_pb2'
  # @@protoc_insertion_point(class_scope:cs.CookieJar)
  ))
_sym_db.RegisterMessage(CookieJar)


# @@protoc_insertion_point(module_scope)
