/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cookie_store.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cookie_store.pb-c.h"
void   cs__cookie__init
                     (Cs__Cookie         *message)
{
  static const Cs__Cookie init_value = CS__COOKIE__INIT;
  *message = init_value;
}
size_t cs__cookie__get_packed_size
                     (const Cs__Cookie *message)
{
  assert(message->base.descriptor == &cs__cookie__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cs__cookie__pack
                     (const Cs__Cookie *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cs__cookie__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cs__cookie__pack_to_buffer
                     (const Cs__Cookie *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cs__cookie__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cs__Cookie *
       cs__cookie__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cs__Cookie *)
     protobuf_c_message_unpack (&cs__cookie__descriptor,
                                allocator, len, data);
}
void   cs__cookie__free_unpacked
                     (Cs__Cookie *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cs__cookie__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cs__cookie_jar__init
                     (Cs__CookieJar         *message)
{
  static const Cs__CookieJar init_value = CS__COOKIE_JAR__INIT;
  *message = init_value;
}
size_t cs__cookie_jar__get_packed_size
                     (const Cs__CookieJar *message)
{
  assert(message->base.descriptor == &cs__cookie_jar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cs__cookie_jar__pack
                     (const Cs__CookieJar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cs__cookie_jar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cs__cookie_jar__pack_to_buffer
                     (const Cs__CookieJar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cs__cookie_jar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cs__CookieJar *
       cs__cookie_jar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cs__CookieJar *)
     protobuf_c_message_unpack (&cs__cookie_jar__descriptor,
                                allocator, len, data);
}
void   cs__cookie_jar__free_unpacked
                     (Cs__CookieJar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cs__cookie_jar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cs__cookie__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cs__Cookie, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cs__Cookie, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cs__Cookie, domain),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cs__Cookie, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secure",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Cs__Cookie, secure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "httpOnly",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Cs__Cookie, httponly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expirationTime",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Cs__Cookie, expirationtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cs__cookie__field_indices_by_name[] = {
  2,   /* field[2] = domain */
  6,   /* field[6] = expirationTime */
  5,   /* field[5] = httpOnly */
  0,   /* field[0] = name */
  3,   /* field[3] = path */
  4,   /* field[4] = secure */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange cs__cookie__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cs__cookie__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cs.Cookie",
  "Cookie",
  "Cs__Cookie",
  "cs",
  sizeof(Cs__Cookie),
  7,
  cs__cookie__field_descriptors,
  cs__cookie__field_indices_by_name,
  1,  cs__cookie__number_ranges,
  (ProtobufCMessageInit) cs__cookie__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cs__cookie_jar__field_descriptors[1] =
{
  {
    "cookies",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Cs__CookieJar, n_cookies),
    offsetof(Cs__CookieJar, cookies),
    &cs__cookie__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cs__cookie_jar__field_indices_by_name[] = {
  0,   /* field[0] = cookies */
};
static const ProtobufCIntRange cs__cookie_jar__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cs__cookie_jar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cs.CookieJar",
  "CookieJar",
  "Cs__CookieJar",
  "cs",
  sizeof(Cs__CookieJar),
  1,
  cs__cookie_jar__field_descriptors,
  cs__cookie_jar__field_indices_by_name,
  1,  cs__cookie_jar__number_ranges,
  (ProtobufCMessageInit) cs__cookie_jar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
